/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rk4qVIBd3ez
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function ToolboxCart() {
  return (
   
    (<div className="flex flex-col bg-white shadow-md rounded-lg p-4 w-80">
      <h2 className="font-semibold text-lg mb-4">Toolbox Cart</h2>
      <div className="flex flex-col gap-4">
        <div className="flex items-start gap-4">
          <img
            alt="Product image"
            className="aspect-square rounded-md object-cover"
            height="64"
            src="/placeholder.svg"
            width="64" />
          <div className="flex flex-col gap-2">
            <span className="font-medium">Hammer</span>
            <Input className="w-16" defaultValue="1" type="number" />
            <span>$15.99</span>
          </div>
          <Button size="icon" variant="outline">
            <TrashIcon className="h-4 w-4" />
            <span className="sr-only">Remove</span>
          </Button>
        </div>
        <div className="flex items-start gap-4">
          <img
            alt="Product image"
            className="aspect-square rounded-md object-cover"
            height="64"
            src="/placeholder.svg"
            width="64" />
          <div className="flex flex-col gap-2">
            <span className="font-medium">Screwdriver</span>
            <Input className="w-16" defaultValue="1" type="number" />
            <span>$9.99</span>
          </div>
          <Button size="icon" variant="outline">
            <TrashIcon className="h-4 w-4" />
            <span className="sr-only">Remove</span>
          </Button>
        </div>
      </div>
      <div className="flex items-center mt-4">
        <span className="font-medium">Total</span>
        <span className="ml-auto font-medium">$25.98</span>
      </div>
      <div className="flex gap-2 mt-4">
        <Button className="flex-1" variant="outline">
          Continue Shopping
        </Button>
        <Button className="flex-1">Checkout</Button>
      </div>
    </div>)
  );
}


function TrashIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>)
  );
}
